config/routes.rb
Rails.application.routes.draw do
  resources :shared_websites
  # get '/keywords', to: 'keywords#index'
  resources :websites, exept: %i[new edit] do
    get 'search/add_ranks'
    resources :keywords do
      get 'search/create'
    end
  end
  devise_for :users
  root to: 'websites#index'


  require 'sidekiq/web'

  Rails.application.routes.draw do
    # ...
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_flashes.html.erb
  <% if notice %>
    <div class="alert alert-info alert-dismissible fade show m-1" role="alert" >
      <button type="button" class="btn" data-bs-dismiss="alert" aria-label="Close">
        <i class="fa-solid fa-xmark"></i>
      </button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
      <button type="button" class="btn" data-bs-dismiss="alert" aria-label="Close">
        <i class="fa-solid fa-xmark"></i>
      </button>
      <%= alert %>
    </div>
  <% end %>

app/views/shared/_footer.html.erb
<footer class="content-footer footer bg-footer-theme">
              <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                <div class="mb-2 mb-md-0">
                  ©
                  נבנה על ידי אור גרנות
                </div>
                <div>
                  <a href="https://themeselection.com/license/" class="footer-link me-4" target="_blank">License</a>

                  <a href="https://themeselection.com/" target="_blank" class="footer-link me-4">More Themes</a>

                  <a
                    href="https://themeselection.com/demo/sneat-bootstrap-html-admin-template/documentation/"
                    target="_blank"
                    class="footer-link me-4"
                    >Documentation</a
                  >

                  <a
                    href="https://github.com/themeselection/sneat-html-admin-template-free/issues"
                    target="_blank"
                    class="footer-link me-4"
                    >Support</a
                  >
                </div>
              </div>
            </footer>

app/views/shared/_keywords.html.erb
<% keywords.each do |keyword| %>
  <% last_search = keyword.searches.first %>
  <tr>
    <td class="sticky-cell-options">
      <div class="d-flex gap-1">
        <%= link_to website_keyword_search_create_path(@website,keyword), class: "keyword-option" do %>
          <i class="text-primary fa-solid fa-arrows-rotate"></i>
        <% end %>
        <%= link_to website_keyword_path(@website, keyword), data: {"turbo-method": :delete, turbo_confirm: 'אתה בטוח? כל המידע יאבד' }, class: "text-danger" do %>
          <i class="btn p-0 text-danger">X</i>
        <% end %>
      </div>
    </td>
    <td class="keyword sticky-cell" scope="row"><%= keyword.key_string %></td>
    <% @dates.each do |date| %>
      <% search = keyword.searches.select{|search| search[:date] == date}[0] %>
      <% if search %>
        <% change = 'same-rank' if search.rank.to_i == last_search.rank.to_i
          change = 'lower-rank' if search.rank.to_i > last_search.rank.to_i
          change = 'higher-rank' if search.rank.to_i < last_search.rank.to_i %>
        <td class = "<%= "rank " + change %>"><%= search.rank %></td>
      <% else %>
        <td class = "rank"> - </td>
      <% end %>
      <% last_search = search unless search.nil? %>
    <% end %>
  </tr>
<% end %>

app/views/shared/_logo.html.erb
<%= link_to root_path, class: 'app-brand-link' do %>
  <span class="app-brand-logo demo">
    <i class="fs-4 fa fa-thin fa-chart-line"></i>
  </span>
  <span class="app-brand-title demo h4 mb-0 menu-text fw-bolder me-1"><span class="">Seo</span>Tracker</span>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
  id="layout-navbar">
  <div class="layout-menu-toggle navbar-nav align-items-xl-center ms-3 me-xl-0 d-xl-none">
    <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
      <i class="bx bx-menu bx-sm"></i>
    </a>
  </div>

  <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
    <ul class="navbar-nav flex-row align-items-center flex-grow-1 p-0 gap-3">
      <!-- User -->
      <li class="nav-item d-flex align-items-center">
        <% if user_signed_in? %>
          <div class="avatar avatar-offline">
            <img src="/../sneat-1.0.0/assets/img/avatars/avatar-user-guest.png" alt class="w-px-40 h-auto rounded-circle" />
          </div>
        <% else %>
          <%= render 'shared/logo' %>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= current_user.email %>
        </li>
      <% end %>
      <div class="nav-item d-flex align-items-center me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= button_to "התנתקות", destroy_user_session_path, method: :delete, data: { turbo: false }  ,class: "btn nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "התחברות", new_user_session_path, class: "nav-link" %>
          </li>
          |
          <li class="nav-item">
            <%= link_to "הרשמה", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </div>


      <!--/ User -->
    </ul>
  </div>
</nav>

app/views/shared/_shared_users.html.erb
<div class="d-flex ">
  <% users = website.shared_users.map { |user| user.email.partition('@').first } %>
  <% if users %>
    <span class="text-muted text-small h6 m-0">
    <% if users.length == 1 %>
      <%= users.first %> משותף
    <% elsif users.length > 3 %>
      <%= users.first(3).join(', ') %> ועוד <%= users.length - 3 %> משותפים
    <% else %>
      <%= users.first(users.length - 1).join(', ') %> ו<%= users.last %> משותפים
    <% end %>
  <% end %>
  </span>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <h2>sidebar</h2>
</div>

app/views/shared/_sidenav.html.erb
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
  <div class="app-brand demo">
    <%= render 'shared/logo' %>

    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
      <i class="bx bx-chevron-left bx-sm align-middle"></i>
    </a>
  </div>

  <div class="menu-inner-shadow"></div>

  <ul class="menu-inner py-1" data-controller="menu">
    <!-- Dashboard -->
    <li class="menu-item  <%= current_class?(websites_path) %> ">
      <%= link_to websites_path, class: 'menu-link', data: { "turbo-frame": "content"} do %>
          <i class="menu-icon tf-icons bx bx-home-circle"></i>
          <div data-i18n="Analytics">לוח מנהל</div>
      <% end %>
    </li>

    <!-- Layouts -->


    <li class="menu-header small text-uppercase">
      <span class="menu-header-text">מיקום אתרים</span>
    </li>

    <li class="menu-item dropdown">
      <button class="btn menu-link menu-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="menu-icon tf-icons bx bx-dock-top m-0 ms-1"></i>
        האתרים שלי
      </button>
      <ul class="menu-sub">
        <% @websites.each do |website| %>
          <li class="menu-item <%= current_class?(website_path(website)) %> ">
            <%= link_to website, class: "menu-link", data: { "turbo-frame": "content"} do %>
              <div data-i18n="Account"><%= website.name %></div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </li>
    <li class="menu-item dropdown">
      <button class="btn menu-link menu-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="menu-icon tf-icons bx bx-dock-top m-0 ms-1"></i>
        משותפים איתי
      </button>

      <ul class="menu-sub">
        <% @shared_websites.each do |website| %>
          <li class="menu-item <%= current_class?(shared_website_path(website.id)) %> ">
            <%= link_to website.website, class: "menu-link", data: { "turbo-frame": "content"} do %>
              <div data-i18n="Account"><%= website.website.name %></div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </li>

    <li class="menu-item text-center mt-2">
      <button
        type="button"
        class="btn btn-outline-primary btn-sm"
        data-bs-toggle="modal"
        data-bs-target="#newWebsiteSideBar"
      >
        אתר חדש
      </button>
    </li>

    <li class="menu-header small text-uppercase">
      <span class="menu-header-text">בדיקת לינקים</span>
    </li>

  </ul>
</aside>
<div class="modal fade" id="newWebsite" data-bs-backdrop="static" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title mt-4 text-primary" id="backDropModalTitle">הוספת אתר חדש</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <%= render 'websites/form', tag: "צור", new: false %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="newWebsiteSideBar" data-bs-backdrop="static" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title mt-4 text-primary" id="backDropModalTitle">הוספת אתר חדש</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <%= render 'websites/form', tag: "צור", new: true %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_table.html.erb
<%= turbo_frame_tag("keywords") do %>
  <table class="table table-striped" >
    <thead class="bg-white">
      <tr>
        <th class="bg-white sticky-cell-options text-center" scope="col">
        </th>
        <th class="sticky-cell" scope="col"><%= sort_link(@q, :created_at, "מילות חיפוש", default_order: :asc) %></th>
        <% @dates.each do |date| %>
          <th scope="col" class="date">
            <%= link_to website_path(@website), data: { "turbo-frame": "keywords" } do %>
              <%= date.strftime('%d/%m/%Y')%>
            <% end %>
          </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td colspan="100%" class="text-end">
          <%= turbo_frame_tag("add-keyword") do %>
          <% end %>
        </td>
      </tr>
      <%= render 'shared/keywords', keywords: @keywords %>
    </tbody>
  </table>
<% end %>

app/views/shared/_table_card.html.erb
<div class="card">
  <div class="card-header d-flex justify-content-between align-items-center">
    <div class="d-flex align-items-center gap-2 w-100">
      <h2 class="m-0 text-center fw-bold text-primary">
        <%= website.name %>
      </h2>
      <div class="h6 mt-2 mb-0 flex-grow-1">(
        <%= link_to URI::HTTP.build({:host => website.url}).to_s, class: 'text-muted dropdown-link', target: "_blank" do %>
          <i class="text-muted fa-solid fa-arrow-up-right-from-square"></i>
          <%= website.url %>
        <% end %>
      )</div>
      <div class="website-links d-flex align-items-center">
        <% if role == 'owner' %>
          <%= link_to new_website_keyword_path(website), data: { "turbo-frame": "add-keyword" }, class: "btn" do %>
            <i class="fa-sharp fa-solid fa-plus"></i>
          <% end %>
          <button
            type="button"
            class="btn"
            data-bs-toggle="modal"
            data-bs-target="#shareWebsiteModal"
          >
            <i class="fa-solid fa-user-plus"></i>
          </button>
          <button
            type="button"
            class="btn"
            data-bs-toggle="modal"
            data-bs-target="#editWebsiteModal"
          >
            <i class="fa-regular fa-pen-to-square"></i>
          </button>
          <%= link_to website, data: { "turbo-method": :delete, turbo_confirm: 'אתה בטוח? כל המידע יאבד' }, class: "btn" do %>
            <i class="text-danger fa-solid fa-trash"></i>
          <% end %>

          <div class="modal fade" id="editWebsiteModal" data-bs-backdrop="static" tabindex="-1">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title mt-4 text-primary" id="backDropModalTitle">עריכה</h5>
                  <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                  ></button>
                </div>
                <div class="modal-body">
                  <%= render 'form', tag: "עדכן", new: false %>
                </div>
              </div>
            </div>
          </div>
          <div class="modal fade" id="shareWebsiteModal" data-bs-backdrop="static" tabindex="-1">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <div class="d-flex align-items-center gap-3 mt-3">
                    <h5 class="modal-title text-primary" id="backDropModalTitle">שיתוף עם איש קשר</h5>
                    <span class="text-muted h6 m-0"><%=website.users_as_string %></span>
                  </div>
                  <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                  ></button>
                </div>
                <div class="modal-body">
                  <%= render 'shared_websites/form', tag: "שתף" %>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <% shared_website = current_user.shared_websites.find_by(website_id: website.id) %>
          <%= button_to shared_website, method: :delete, data: { "turbo-method": :delete, turbo_confirm: 'אתה בטוח? השיתוף ימחק' }, class: "btn" do %>
            <i class="text-danger fa-solid fa-trash"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="" data-controller="table">
    <div class="card-body p-0 pt-3" >
      <% if role == 'owner' %>
        <div class=" d-flex mb-2 me-2">
          <% keyword = Keyword.new %>
            <div class="d-flex" data-controller="search">
              <%= search_form_for(@q, url: website_path(website) , method: :get, data: { turbo_frame: 'content', "search-target": "form" }) do |f|  %>
                <div class="d-flex gap-2 align-items-center">
                  <%= f.search_field :key_string_i_cont_any, placeholder: "חיפוש", class: "form-control", data: { action: "keyup->search#submit", "search-target": "input" } %>
                </div>
              <% end %>
            </div>
        </div>

      <% end %>
      <div class="mb-2" style="overflow-x:auto;" data-table-target="scollable">
        <%= render 'shared/table'%>
      </div>
      <div class="mt-4">
        <%= line_chart @keywords.map { |keyword|
          {name: keyword.key_string, data: keyword.searches.group_by_day(:created_at).maximum(:rank).select { |k,v| v != nil } } }
        %>
      </div>
      <div class="links d-flex justify-content-start align-items-center gap-3 p-3">
        <% if @keywords.length != 0 && role == 'owner'%>
          <%= link_to "בדוק מיקומים", website_search_add_ranks_path(website), class: "btn btn-primary " %>
        <% end %>
        <%= link_to "חזור", websites_path, class: "btn btn-outline-primary " %>
      </div>
    </div>
  </div>
</div>